# ===================================
#  Form Behavior Config
# ===================================

name: FAQ Editor
form: @/plugins/redmarlin/faq/models/question/fields.yaml
modelClass: REDMARLIN\Faq\Models\Question
defaultRedirect: redmarlin/faq/faq

create:
    title: ADD Question
    redirect: redmarlin/faq/faq/update/:id
    redirectClose: redmarlin/faq/faq
    flashSave: Question added correctly.

update:
    title: Edit Question
    redirect: redmarlin/faq/faq
    redirectClose: redmarlin/faq/faq
    flashSave: QUESTION updated successfully!
    flashDelete: Question has been deleted.